# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSVideoPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoSwiftyM3U8', '~> 1.0.0'
  pod 'NVActivityIndicatorView', '~> 4.0.0'

  # Pods for FSVideoPlayer

  target 'FSVideoPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
