//
//  VideoPlayerPresenter.swift
//  fschool_ios
//
//  Created Ilya Glazunov on 14/06/2018.
//  Copyright © 2018 Altarix. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AVFoundation

class VideoPlayerPresenter: VideoPlayerPresenterProtocol {

    weak private var view: VideoPlayerViewProtocol?
    var interactor: VideoPlayerInteractorInputProtocol?
    private let router: VideoPlayerWireframeProtocol

    init(interface: VideoPlayerViewProtocol, interactor: VideoPlayerInteractorInputProtocol?, router: VideoPlayerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getTimeString(from time: CMTime) -> String {
        let totalSeconds = CMTimeGetSeconds(time)
        let hours = Int(totalSeconds/3600)
        let minutes = Int(totalSeconds/60) % 60
        let seconds = Int(totalSeconds.truncatingRemainder(dividingBy: 60))
        if hours > 0 {
            return String(format: "%i:%02i:%02i", arguments: [hours,minutes,seconds])
        }else {
            return String(format: "%02i:%02i", arguments: [minutes,seconds])
        }
    }
}

extension VideoPlayerPresenter: VideoPlayerInteractorOutputProtocol {
    
}
