//
//  VideoPlayerInteractor.swift
//  fschool_ios
//
//  Created Ilya Glazunov on 14/06/2018.
//  Copyright © 2018 Altarix. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoPlayerInteractor: VideoPlayerInteractorInputProtocol {

    weak var presenter: VideoPlayerInteractorOutputProtocol?
}
