//
//  VideoPlayerPresenter.swift
//  fschool_ios
//
//  Created Ilya Glazunov on 14/06/2018.
//  Copyright © 2018 Altarix. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoPlayerPresenter: VideoPlayerPresenterProtocol, VideoPlayerInteractorOutputProtocol {

    weak private var view: VideoPlayerViewProtocol?
    var interactor: VideoPlayerInteractorInputProtocol?
    private let router: VideoPlayerWireframeProtocol

    init(interface: VideoPlayerViewProtocol, interactor: VideoPlayerInteractorInputProtocol?, router: VideoPlayerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
