//
//  VideoPlayerProtocols.swift
//  fschool_ios
//
//  Created Ilya Glazunov on 14/06/2018.
//  Copyright © 2018 Altarix. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import AVFoundation

//MARK: Wireframe -
protocol VideoPlayerWireframeProtocol: class {

}
//MARK: Presenter -
protocol VideoPlayerPresenterProtocol: class {

    var interactor: VideoPlayerInteractorInputProtocol? { get set }
    func getTimeString(from time: CMTime) -> String 
}

//MARK: Interactor -
protocol VideoPlayerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol VideoPlayerInteractorInputProtocol: class {

    var presenter: VideoPlayerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol VideoPlayerViewProtocol: class {

    var presenter: VideoPlayerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
