//
//  VideoPlayerRouter.swift
//  fschool_ios
//
//  Created Ilya Glazunov on 14/06/2018.
//  Copyright © 2018 Altarix. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoPlayerRouter: VideoPlayerWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(with view: VideoPlayerViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = VideoPlayerInteractor()
        let router = VideoPlayerRouter()
        let presenter = VideoPlayerPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
}
